name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]  # change to "master" if that's your default branch

permissions:
  contents: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install deps
        run: npm ci

      # Set the correct base path so CSS/JS load from /upgrade-wellness-center/_next/...
      - name: Configure base path
        run: echo "NEXT_PUBLIC_BASE_PATH=/upgrade-wellness-center" >> .env.production

      - name: Build (Next.js static export to /out)
        env:
          CI: true
        run: npm run build

      # Ensure Pages serves underscored dirs (/_next). Next export usually adds this,
      # but this is harmless if it already exists.
      - name: Add .nojekyll
        run: touch out/.nojekyll

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
          force_orphan: true
