name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]   # change if your default is different
  workflow_dispatch:

permissions:
  contents: write   # needed by peaceiris/actions-gh-pages

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install deps
        run: npm ci

      # Build + export with the correct base path for GH Pages
      # (your script: sets NEXT_PUBLIC_BASE_PATH and runs next build && next export)
      - name: Build (Next.js static export to /out)
        env:
          CI: true
        run: npm run build:pages

      # Ensure Pages serves underscored dirs like /_next
      - name: Add .nojekyll
        run: |
          mkdir -p out
          touch out/.nojekyll

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./out
          force_orphan: true
          commit_message: "Deploy: ${{ github.sha }}"
