name: Deploy Next.js site to GitHub Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      # Make assets load from /<repo>/_next/... on GitHub Pages
      NEXT_PUBLIC_BASE_PATH: "/${{ github.event.repository.name }}"
      CI: "true"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build & Export static site
        run: |
          npx next build
          npx next export
          # Ensure Pages serves the _next/ folder
          mkdir -p out
          touch out/.nojekyll

      # --- Optional debug to verify correct paths & files ---
      - name: Debug base path + asset list
        run: |
          echo "NEXT_PUBLIC_BASE_PATH=$NEXT_PUBLIC_BASE_PATH"
          echo "CSS refs found in out/index.html:"
          grep -o '/.*_next/static/[^\" ]*\.css' -h out/index.html || true
          echo "Files under out/_next/static:"
          find out/_next/static -maxdepth 3 -type f -print || true

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./out

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
